openapi: 3.0.1
info:
  title: Caddy Delivery Network - Worker API
  version: 0.0.0
servers:
  - url: /api/worker
paths:
  /{id}/heartbeat:
    get:
      tags:
        - worker
      summary: heartbeat event
      security:
        - TokenAuth: []
      operationId: heartbeat
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HeartbeatRes"
        404:
          description: No such instance (deleted or token mismatch)
        500:
          description: Internal server error

  /{id}/config:
    get:
      tags:
        - worker
      summary: get config
      security:
        - TokenAuth: []
      operationId: getConfig
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Success
          content:
            text/caddyfile: # text
              schema:
                type: string
        404:
          description: No such instance (deleted or token mismatch)
        500:
          description: Internal server error

  /{id}/file:
    get:
      tags:
        - worker
      summary: get single file
      security:
        - TokenAuth: []
      operationId: getFiles
      parameters:
        - $ref: '#/components/parameters/id'
        - in: header
          name: X-File-Path
          description: Path of target file
          schema:
            type: string
      responses:
        200:
          description: Success
          headers:
            X-Updated-At:
              description: Update timestamp of target file
              schema:
                $ref: "#/components/schemas/timestamp"
          content:
            application/octet-stream: # binary
              schema:
                type: string
                format: binary
        404:
          description: No such instance (deleted or token mismatch) or file
        500:
          description: Internal server error

components:
  securitySchemes:
    TokenAuth:
      type: http
      scheme: bearer
  parameters:
    id:
      name: id
      in: path
      description: ID
      schema:
        type: integer
        format: uint
  schemas:
    timestamp:
      type: integer
      format: int64
      description: unix second
    HeartbeatRes:
      type: object
      required:
        - config_updated_at
        - files_updated_at
      properties:
        config_updated_at:
          $ref: "#/components/schemas/timestamp"
        files_updated_at:
          type: array
          items:
            $ref: "#/components/schemas/FileUpdateRecord"
    FileUpdateRecord:
      type: object
      required:
        - path
        - updated_at
      properties:
        path:
          type: string
        updated_at:
          $ref: "#/components/schemas/timestamp"
